services:
  pjautomation-ui:
    build:
      context: .
    container_name: pjautomation-ui
    networks:
      - npm-network
    restart: always
    ports:
      - 3001:80   # Host port : Container port (you can change 3001 if needed)
